services:
  web:
    build: .
    container_name: app-web
    env_file: .env.prod
    command: >
      bash -lc "
      python manage.py migrate &&
      gunicorn nutrition_app.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks: [appnet]

  db:
    image: postgres:16
    container_name: app-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    depends_on:
      - web
    ports:
      - "80:80"
      # En producción real usa 443 con certificados (ver abajo)
      # - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/static:ro
    networks: [appnet]

volumes:
  pg_data:
  static_data:

networks:
  appnet:
    driver: bridge